name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js (you can adjust the version)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: Install dependencies and build the project
    - name: Install dependencies and build
      run: |
        cd nomauclature
        npm install
        npm run build

    # Step 4: Deploy `dist` folder to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: main          # Deploy directly to the main branch
        folder: nomauclature/dist  # Specify the build folder
