name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  

      - name: Set up Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: '18'  

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Run the build script (ensure it outputs to 'dist')

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Deploy using GitHub Pages action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          publish_dir: ./dist  